language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_script: composer update
script: vendor/bin/phpunit test\
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
install:
    pip install codecov
